module.exports = {
  urlMessageError: 'неверный формат ссылки',
  emailMessageError: 'неверный формат email',
  emailDoubleError: 'пользователь с такой почтой уже существует',
  emailOrPassError: 'Неправильные почта или пароль',
  userNotExistError: 'пользователь не существует',
  articlesNotExistError: 'статьи не найдены',
  articleNotExistError: 'статья не существует',
  noRightsArticleDelError: 'нет прав на удаление статьи',
  authError: 'ошибка авторизации',
  registrationNameError: 'Введите Ваше имя',
  registrationEmailError: 'Введите Ваш email',
  registrationPassError: 'Введите Ваш пароль',
  incorrectEmailOrPassError: 'Неправильный email или пароль',
  notKeyworldError: 'Отсутствует ключевое слово',
  notTitleError: 'Отсутствует название статьи',
  notTextErorr: 'Отсутствует текст статьи',
  notDateErorr: 'Отсутствует дата публикации статьи',
  notSourceErorr: 'Отсутствует источник статьи',
  notLinkErorr: 'Отсутствует ссылка на статью',
  notImageErorr: 'Отсутствует иллюстрация к статье',
  notArticleIdError: 'Статья не найдена',
  serverMessageError: 'Ошибка сервера',
};
